### ISSUE TITLE
SQS - Failed message cause failedDelete to grow forever.

### ISSUE THREAD

**Issue by mgale** [evalphobia/aws-sdk-go-wrapper#70]
From the looks of things I think q.failedDelete will grow forever:
I only see it being appended to here:
https://github.com/evalphobia/aws-sdk-go-wrapper/blob/master/sqs/queue.go#L159

And GetQueue will pull it from a cache:
https://github.com/evalphobia/aws-sdk-go-wrapper/blob/master/sqs/client.go#L59

**Comment by evalphobia** [comment]
@mgale  Thank you for your reporting.

It should be solved at the time of sending/deleting and library users should not worry about it, but it seemed to need to change the method signature.
So I added `GetFailedResults` and `ClearFailedResults` for now.
https://github.com/evalphobia/aws-sdk-go-wrapper/pull/73

**Comment by mgale** [comment]
Thanks for looking into this.
